package supermercado.view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

public class CalculoMargemFrame extends javax.swing.JInternalFrame implements CalculoMargemView {

    private static final long serialVersionUID = 1L;
    private static final DateTimeFormatter FORMATO_DATA = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    private final DefaultTableModel modeloResultados;
    private final SeletorData seletorData;
    private transient Runnable acaoCalcular;
    private transient Runnable acaoFechar;

    public CalculoMargemFrame() {
        initComponents();
        modeloResultados = UtilSwing.configurarTabela(tblResultados, "Nome do produto", "Preço unitário",
                "Categoria", "Percentual de lucro", "Preço de venda calculado");
        UtilSwing.definirLarguras(tblResultados, 240, 100, 130, 110, 150);
        UtilSwing.alinharColunas(tblResultados, SwingConstants.RIGHT, 1, 3, 4);
        seletorData = new SeletorData(data -> txtData.setText(data.format(FORMATO_DATA)));

        btnCalendario.addActionListener(e -> seletorData.exibir(txtData, dataDigitada()));
        btnCalcular.addActionListener(e -> UtilSwing.executar(acaoCalcular));
        txtData.addActionListener(e -> UtilSwing.executar(acaoCalcular));
        btnFechar.addActionListener(e -> UtilSwing.executar(acaoFechar));
        UtilSwing.aoFechar(this, () -> UtilSwing.executar(acaoFechar));
    }

    private LocalDate dataDigitada() {
        try {
            return LocalDate.parse(txtData.getText().trim(), FORMATO_DATA);
        } catch (DateTimeParseException e) {
            return null;
        }
    }

    @Override
    public String getDataCalculo() {
        return txtData.getText();
    }

    @Override
    public void setDataCalculo(String data) {
        txtData.setText(data);
    }

    @Override
    public void setResultados(List<String[]> linhas) {
        UtilSwing.substituirLinhas(modeloResultados, linhas);
    }

    @Override
    public void setAcaoCalcular(Runnable acao) {
        acaoCalcular = acao;
    }

    @Override
    public void fechar() {
        UtilSwing.fechar(this);
    }

    @Override
    public boolean estaAberta() {
        return !isClosed();
    }

    @Override
    public void trazerParaFrente() {
        UtilSwing.trazerParaFrente(this);
    }

    @Override
    public void setAcaoFechar(Runnable acao) {
        acaoFechar = acao;
    }

    @Override
    public void mostrarSucesso(String mensagem) {
        UtilSwing.mostrarSucesso(this, mensagem);
    }

    @Override
    public void mostrarAviso(String mensagem) {
        UtilSwing.mostrarAviso(this, mensagem);
    }

    @Override
    public void mostrarErro(String mensagem) {
        UtilSwing.mostrarErro(this, mensagem);
    }

    @Override
    public boolean confirmar(String titulo, String mensagem) {
        return UtilSwing.confirmar(this, titulo, mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btnCalendario = new javax.swing.plaf.basic.BasicArrowButton(javax.swing.SwingConstants.SOUTH);
        btnCalcular = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        scrResultados = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cálculo de Margem de Lucro");

        pnlFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        lblData.setText("Data do cálculo");

        txtData.setToolTipText("Formato dd/mm/aaaa");

        btnCalendario.setToolTipText("Escolher a data no calendário");

        btnCalcular.setText("Calcular");

        lblAviso.setText("O cálculo só pode ser realizado novamente após 10 dias.");

        javax.swing.GroupLayout pnlFiltrosLayout = new javax.swing.GroupLayout(pnlFiltros);
        pnlFiltros.setLayout(pnlFiltrosLayout);
        pnlFiltrosLayout.setHorizontalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(24, 24, 24)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAviso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltrosLayout.setVerticalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblData)
                    .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAviso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrResultados.setViewportView(tblResultados);

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblData;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JScrollPane scrResultados;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
